version: "3.8"

services:
  nginx:
    container_name: nginx
    restart: always
    image: nginx:stable-alpine
    ports:
      - 443:443
    volumes:
      - ./nginx:/etc/nginx
      - nginx-log:/var/log/nginx
    networks:
      - default
      - proxy

volumes:
  nginx-log:

networks:
  default:
     driver: bridge
  proxy:
    external: true
    name: proxy
